/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Goal = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'reason' : IDL.Text,
});
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'userId' : IDL.Principal,
  'date' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'completed' : IDL.Bool,
  'goalId' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'completeTask' : IDL.Func([IDL.Nat], [], []),
  'createGoal' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'createTask' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [IDL.Nat], []),
  'deleteGoal' : IDL.Func([IDL.Nat], [], []),
  'deleteTask' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCompletedTaskCountToday' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getCompletedTaskDatesForCurrentUser' : IDL.Func(
      [],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getGoalsForCurrentUser' : IDL.Func([], [IDL.Vec(Goal)], ['query']),
  'getTasksForCurrentUser' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getTasksForDate' : IDL.Func([IDL.Text], [IDL.Vec(Task)], ['query']),
  'getTasksForGoal' : IDL.Func([IDL.Nat], [IDL.Vec(Task)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'uncompleteTask' : IDL.Func([IDL.Nat], [], []),
  'updateGoal' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'updateTask' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Goal = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'reason' : IDL.Text,
  });
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'userId' : IDL.Principal,
    'date' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'completed' : IDL.Bool,
    'goalId' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'completeTask' : IDL.Func([IDL.Nat], [], []),
    'createGoal' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'createTask' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [IDL.Nat], []),
    'deleteGoal' : IDL.Func([IDL.Nat], [], []),
    'deleteTask' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCompletedTaskCountToday' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getCompletedTaskDatesForCurrentUser' : IDL.Func(
        [],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getGoalsForCurrentUser' : IDL.Func([], [IDL.Vec(Goal)], ['query']),
    'getTasksForCurrentUser' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getTasksForDate' : IDL.Func([IDL.Text], [IDL.Vec(Task)], ['query']),
    'getTasksForGoal' : IDL.Func([IDL.Nat], [IDL.Vec(Task)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'uncompleteTask' : IDL.Func([IDL.Nat], [], []),
    'updateGoal' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'updateTask' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };