/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Goal {
  'id' : bigint,
  'title' : string,
  'userId' : Principal,
  'createdAt' : bigint,
  'reason' : string,
}
export interface Task {
  'id' : bigint,
  'userId' : Principal,
  'date' : string,
  'name' : string,
  'createdAt' : bigint,
  'completed' : boolean,
  'goalId' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'completeTask' : ActorMethod<[bigint], undefined>,
  'createGoal' : ActorMethod<[string, string], bigint>,
  'createTask' : ActorMethod<[string, string, bigint], bigint>,
  'deleteGoal' : ActorMethod<[bigint], undefined>,
  'deleteTask' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCompletedTaskCountToday' : ActorMethod<[string], bigint>,
  'getCompletedTaskDatesForCurrentUser' : ActorMethod<[], Array<string>>,
  'getGoalsForCurrentUser' : ActorMethod<[], Array<Goal>>,
  'getTasksForCurrentUser' : ActorMethod<[], Array<Task>>,
  'getTasksForDate' : ActorMethod<[string], Array<Task>>,
  'getTasksForGoal' : ActorMethod<[bigint], Array<Task>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'uncompleteTask' : ActorMethod<[bigint], undefined>,
  'updateGoal' : ActorMethod<[bigint, string, string], undefined>,
  'updateTask' : ActorMethod<[bigint, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];